package common; 

public enum Action {
    // Reservation Actions
    GET_RESERVATION,
    CREATE_RESERVATION,
    UPDATE_RESERVATION,
    CANCEL_RESERVATION,
    RESERVATION_NOT_CREATED,
    RESERVATION_NOT_FOUND,
    GET_VERIFICATION_CODE,
    SEND_VERIFICATION_CODE,
    
    // Guest Actions
    GET_GUEST,
    
    // Connection Actions
    DISCONNECT,
    
    //Member Actions
    GET_MEMBER,
    CREATE_MEMBER,
    MEMBER_NOT_CREATED,
    UPDATE_MEMBER,
    DELETE_MEMBER,
    MEMBER_IDENTIFICATION,
    MEMBER_NOT_FOUND,
    GET_MEMBER_VISITS,
    
    //Visit Actions
    CREATE_VISIT,
    GET_VISIT,
    START_VISIT,
    END_VISIT,
    CANCEL_VISIT,
    VISIT_NOW,
    
    //BILL ACTIONS
    GET_BILL,
    UPDATE_BILL, 
    
    //STAFF ACTIONS
    STAFF_IDENTIFICATION,
    STAFF_NOT_FOUND,
    
    //RESTAURANT ACTIONS
    GET_RESTAURANT_CONFIG,
    UPDATE_RESTAURANT_CONFIG,
    
    //MANAGEMENT ACTIONS
    CHECK_IN_CUSTOMER,
    VERIFY_MEMBER_ARRIVAL,
    GENERATE_REPORT,
    GET_ACTIVE_VISITS,
    
    //TABLE ACTIONS
    GET_ALL_TABLES,
    UPDATE_TABLE,
    DELETE_TABLE,
    ADD_TABLE,
}
