package common; 

public enum Action {
    // Reservation Actions
    GET_RESERVATION,
    CREATE_RESERVATION,
    UPDATE_RESERVATION,
    CANCEL_RESERVATION,
    RESERVATION_NOT_CREATED,
    RESERVATION_NOT_FOUND,
    GET_VERIFICATION_CODE,
    GET_MEMBER_RESERVATIONS,
    CHECK_RESERVATION_AVAILABILITY,
    FIND_RESERVATION,
    // Connection Actions
    DISCONNECT,
    //Member Actions
    CREATE_MEMBER,
    MEMBER_NOT_CREATED,
    UPDATE_MEMBER,
    DELETE_MEMBER,
    MEMBER_IDENTIFICATION,
    MEMBER_NOT_FOUND,
    GET_MEMBER_VISITS,
    //Visit Actions
    START_VISIT,
    END_VISIT, //NOT IN USE
    CANCEL_VISIT, //NOT IN USE
    VISIT_NOW,
    //BILL ACTIONS
    UPDATE_BILL, 
    //STAFF ACTIONS
    STAFF_IDENTIFICATION,
    STAFF_NOT_FOUND,
    //RESTAURANT ACTIONS
    GET_RESTAURANT_CONFIG, //NOT IN USE
    UPDATE_RESTAURANT_CONFIG, //NOT IN USE
    //MANAGEMENT ACTIONS
    CHECK_IN_CUSTOMER,
    VERIFY_MEMBER_ARRIVAL,
    GENERATE_REPORT, //NOT IN USE
    GET_ACTIVE_VISITS,
    GET_WAITING_LIST,
    REMOVE_FROM_WAITING_LIST, 
    //TABLE ACTIONS
    GET_ALL_TABLES,
    UPDATE_TABLE,
    DELETE_TABLE,
    ADD_TABLE, 
}
